export * from './types'
export { BasicInfoTab } from './BasicInfoTab'
export { DescriptionTab } from './DescriptionTab'
export { LessonsTab } from './LessonsTab'
export { ScheduleTab } from './ScheduleTab'
export { VodSettingsTab } from './VodSettingsTab'
